name: Publish Website to Web Hosting V2
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER_SMS }}
        username: ${{ secrets.FTP_USERNAME_SMS }}
        password: ${{ secrets.FTP_PASSWORD_SMS }}
